### PR TITLE
feat: improve mongo support

### PR DESCRIPTION
**Pull request by mhdawson**
- build url needed to connect
- move auth info to the right nesting
- add test for case when port is used

Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
@tchughesiv could you test this out. It should be used as:

```JavaScript
let connectionOptions;
try {
    // check if the deployment has been bound to a pg instance through
    // service bindings. If so use that connect info
    connectionOptions = serviceBindings.getBinding('MONGODB', 'mongodb');
} catch (err) { // proper error handling here
};

const url = connectionOptions + '/' + database + '?retryWrites=true&w=majority';
const client = new MongoClient(url, connectionOptions);
```
passing the connectionOptions to new MongoClient() will allow additional connections to be set through service bindings if/when they are supported/provided.

Note that I did move the username/password to the structure I found in `options` under new MongoClient in - https://mongodb.github.io/node-mongodb-native/3.4/api/MongoClient.html

**Comment by tchughesiv** [comment]
@mhdawson database is not a requirement to connect to cluster
```
const url = bindings.url + '?retryWrites=true&w=majority';
```

**Comment by mhdawson** [comment]
@tchughesiv in terms of the database great if we don't need to add, ideally we could just pass in the results of what we get back from the bindings after having set any additional options needed on the bindings.connectionOptions object.

**Comment by mhdawson** [comment]
@tchughesiv confirmed this PR works for him, landing.

**Pull request merged**
